### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by SniparsZach** [SplitPixl/Cleverbutts#7]
Getting this error

> SyntaxError: Unexpected token =
>    at exports.runInThisContext (vm.js:53:16)
>    at Module._compile (module.js:373:25)
>    at Object.Module._extensions..js (module.js:416:10)
>    at Module.load (module.js:343:32)
>    at Function.Module._load (module.js:300:12)
>    at Function.Module.runMain (module.js:441:10)
>    at startup (node.js:139:18)
>    at node.js:968:3
> /home/ubuntu/workspace/tb_main/cleverbutts.js:147
> function execCommand(msg, cmd, suffix, type = "normal") {

There is a "^" underneath the "=" sign

**Comment by SplitPixl** [comment]
Make sure you are updated to the latest node version
